 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/guizaos", type: :request do
  # Guizao. As you add validations to Guizao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Guizao.create! valid_attributes
      get guizaos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      guizao = Guizao.create! valid_attributes
      get guizao_url(guizao)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_guizao_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      guizao = Guizao.create! valid_attributes
      get edit_guizao_url(guizao)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Guizao" do
        expect {
          post guizaos_url, params: { guizao: valid_attributes }
        }.to change(Guizao, :count).by(1)
      end

      it "redirects to the created guizao" do
        post guizaos_url, params: { guizao: valid_attributes }
        expect(response).to redirect_to(guizao_url(Guizao.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Guizao" do
        expect {
          post guizaos_url, params: { guizao: invalid_attributes }
        }.to change(Guizao, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post guizaos_url, params: { guizao: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested guizao" do
        guizao = Guizao.create! valid_attributes
        patch guizao_url(guizao), params: { guizao: new_attributes }
        guizao.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the guizao" do
        guizao = Guizao.create! valid_attributes
        patch guizao_url(guizao), params: { guizao: new_attributes }
        guizao.reload
        expect(response).to redirect_to(guizao_url(guizao))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        guizao = Guizao.create! valid_attributes
        patch guizao_url(guizao), params: { guizao: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested guizao" do
      guizao = Guizao.create! valid_attributes
      expect {
        delete guizao_url(guizao)
      }.to change(Guizao, :count).by(-1)
    end

    it "redirects to the guizaos list" do
      guizao = Guizao.create! valid_attributes
      delete guizao_url(guizao)
      expect(response).to redirect_to(guizaos_url)
    end
  end
end
